apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
    - port: 8080
  selector:
    app: app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 5
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: sirfragalot
        image: sirfragalot/docker-demo:dcus
        ports:
        - containerPort: 8080
        